### ISSUE TITLE
Licensing and request

### ISSUE THREAD

**Issue by tling2k** [aaronbamberger/gerber_rs274x_parser#1]
Hi Aaron, I am trying to contact with regarding the "gerber_rs274x_parser", my company may be interested in leveraging that technology, we'd like to contact you to discuss more if that's okay with you? Thanks, Tian Ling

**Comment by aaronbamberger** [comment]
Added the BSD 2-clause license to the project, which is what it was always intended to be under, just hadn't gotten around to it yet.
